GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/search/test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjU5NTdkODkzODUzYjMyMDgxOGU3MmYiLCJpYXQiOjE1OTk2OTA3MTI2OTUsImV4cCI6MTU5OTY5MDc5OTA5NX0.FxMpp_8v0LUE_rNmvPgvXchw_2hc7zu__4JvAew8MgrPyM7Q0lgAmqlQazTjcgt9Oz9_Q_2PrVUq7t71JITk2rPBTRqicrDVODbwC75XOLpmnaxQ5wWWYdWnEVyzbeELXAl7zY1fOYbV8UtRGUGlXp1bZuNzjvXM9gu_3IN93pVBsFN1ig5k7X5hiWolftTQ_aBLFXP0vWXKtZDo9BuBDXBag7E5m_xQcGpDgEYQpw3nsn11LE5chgvYC-9tinOYpHSaavkwZbH6NG4Au8K8-dRi8MLxRemlxwX6Vs9RQRC2TFrmFe_eKE2JCxejfFck0PfpETGt5Y5_H7L6humNa4kMP8MKWFHEKuh4RLkfIZUpWwvDw3hHE29H41c3iXnHO_7NitsAhpnWlsmucDonCH_9UpC9y3wwHH6KXGwkjNsfNpPMqTRK8Nrl0WJRJruUv5fELeEfTTWYz8grXYnhq-ry-t8r5i30oAZLxjBcs7nO9xPM5ocUgDyolHSxQfdDXW2SJVmKlmKKL_8Kgi63cS9ooIKqxD5XgJRUF9ZH0hdBlayfC3kowMem3mOaRGuiBeWfv-G-MZwqVJBKGSrNzh7SmRFP2-VXk-s28xH1IPnNPwlvX2vPUM73ZEBuxXapiaGCEz4YbesgNPfKnyWxYO7M2RJKd1fysu3EhvjwEyk
###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Test Person 1",
    "password": "123"
}

###

GET http://localhost:3000/api/user/posts
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjU5NTdkODkzODUzYjMyMDgxOGU3MmYiLCJpYXQiOjE1OTk2OTA3MTI2OTUsImV4cCI6MTU5OTY5MDc5OTA5NX0.FxMpp_8v0LUE_rNmvPgvXchw_2hc7zu__4JvAew8MgrPyM7Q0lgAmqlQazTjcgt9Oz9_Q_2PrVUq7t71JITk2rPBTRqicrDVODbwC75XOLpmnaxQ5wWWYdWnEVyzbeELXAl7zY1fOYbV8UtRGUGlXp1bZuNzjvXM9gu_3IN93pVBsFN1ig5k7X5hiWolftTQ_aBLFXP0vWXKtZDo9BuBDXBag7E5m_xQcGpDgEYQpw3nsn11LE5chgvYC-9tinOYpHSaavkwZbH6NG4Au8K8-dRi8MLxRemlxwX6Vs9RQRC2TFrmFe_eKE2JCxejfFck0PfpETGt5Y5_H7L6humNa4kMP8MKWFHEKuh4RLkfIZUpWwvDw3hHE29H41c3iXnHO_7NitsAhpnWlsmucDonCH_9UpC9y3wwHH6KXGwkjNsfNpPMqTRK8Nrl0WJRJruUv5fELeEfTTWYz8grXYnhq-ry-t8r5i30oAZLxjBcs7nO9xPM5ocUgDyolHSxQfdDXW2SJVmKlmKKL_8Kgi63cS9ooIKqxD5XgJRUF9ZH0hdBlayfC3kowMem3mOaRGuiBeWfv-G-MZwqVJBKGSrNzh7SmRFP2-VXk-s28xH1IPnNPwlvX2vPUM73ZEBuxXapiaGCEz4YbesgNPfKnyWxYO7M2RJKd1fysu3EhvjwEyk