GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/search/testperson

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Test Person 3",
    "password": "123"
}