GET http://localhost:3000/api/user

###

GET http://localhost:3000/api/user/search/test
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmEwODQ5OGEyYjU1YjQ0YmNmNWU1YjgiLCJpYXQiOjE2MDQzNTUyMjQ5OTMsImV4cCI6MTYwNDM1NTMxMTM5M30.ogtHp5Q6-5_Xpy1kYboYrWwiLNKNpFCGQbdgiSKoSlTPE_D5BwaGBE6SUGrXercETzfzs0QeiN9JkqKOaYp8rdpGMu6o3KSWNdjWkW7MutDvo9di1EL8cPCBCy8vo_2Yd2ZBqFX2bdunmN6tsMIsp3XfhQ3Opyrc2WltVHwYfgn4ZM-VwepcESzdikU-_-Ayn-IHerFAU-CBrHxVxZ6vLoww1_iuH_e9GdLIr6AK62YqLPxmmn1AEeZlgUPZiGPweQwOvyPYavY7sFaaBo_3SGlHuUhcFOi9kVzQSxBczzppZJy2dGbjeUyfcFb1EBv2myP18gSvb7V-sJ6QkeTFiwvu3n7Iv9Efs50dx_jOYILEU9MZHiS90igoF6Urbg2Pzh0zEb-QAQMX-Qhq7S1vWxQiVmayF0xj-lYEkSScigmPRdadGrWiyIjodfbpF7lZleWgdDrLTfMCT-Eqw2MsMbcm12n46MXQBaoXYOGWe3Tpxi_Lh9ufclih97rF0PT8_K3emgullXbyHexpIK6_NFKlr2vLsA90y1h63fjAasvDQPpnT3uQN50fcM1TJQBLHT3IPEVP-6-eH-N8xjvIXnBZ33-iQTCq1aaHJGPriPvA3HMTRy-KuJdyvEeU9r7ekbFgGjDhm3rGZqPKK22YulwRn7sT1X0-ALDF0GtOBD8
###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "Test Person 555",
    "password": "123"
}

###

GET http://localhost:3001/api/auth/refresh
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmEwNzQwZWM1NjMwMTQzNmM3ZTA5ODQiLCJpYXQiOjE2MDU1NzI4NTc4NzYsImV4cCI6MTYwNTU3Mjg1Nzg3Nn0.b1qADSPxePZo2mFs7XICIYkguO-dhpemNpW6fMZYQet2UUu-7zCQ6BB7YoxKqob-g75954fL7AP9DYHWKfGx2RHxmVSJATIu_MoNF35NkgyO0wLUE2MN608uG0wqFPnSWGHL_Kbp4Z66iiIebDs9etaGeDsdHQBpTVC0mXM3CSO2naUsmQC06G0OLobRQc8KwcpBEbifWpO6oFdFirjIgN9vh52XrE_arcX9U-wJ2MpmG2NbCPAyBJpKJBx-mqm9wLwekmp-QT21IHb_SJhZ1DbLre0lHTIuj6lOZP6bDlifhl_483DPMf_L8zdgQNwnUqEZGXYrvEPa3G_1h7kw4-tYaW7qQaOvorwMl6Q5eRBVcN6r9rMhBwGUOwHhsBCT80furuZaX_nuXLgdkYKqA1MPTELruCLKHZbZ4MG1f-WE3VCVqJSSe8KUwkbYMheDgJoTXiiax7cW7eWmwWjctgtVLJr2Jmg8x09MTFXmgFjfAiNgMOFKMY7KXS-tniXoI0loIxWWttCOx9pauWmqei1xMHnUJu32EDSxV7u6LIsak30VdmgLfNBlyRthub6KSFMaaRnjNFzF2y2RcprkBTJqpcC9zUBWfEb0arNoMr9dxuLGoMbhFJWOHvbQ0f0eNxytliG7Zs-cdOpjPi6RnAVi1VAT-4JJVZjBavkbhxk


###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "username": "h",
    "password": "h"
}

###

GET http://localhost:3001/api/auth/testjwt
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZmEwODQ5OGEyYjU1YjQ0YmNmNWU1YjgiLCJpYXQiOjE2MDQzNTUyMjQ5OTMsImV4cCI6MTYwNDM1NTMxMTM5M30.ogtHp5Q6-5_Xpy1kYboYrWwiLNKNpFCGQbdgiSKoSlTPE_D5BwaGBE6SUGrXercETzfzs0QeiN9JkqKOaYp8rdpGMu6o3KSWNdjWkW7MutDvo9di1EL8cPCBCy8vo_2Yd2ZBqFX2bdunmN6tsMIsp3XfhQ3Opyrc2WltVHwYfgn4ZM-VwepcESzdikU-_-Ayn-IHerFAU-CBrHxVxZ6vLoww1_iuH_e9GdLIr6AK62YqLPxmmn1AEeZlgUPZiGPweQwOvyPYavY7sFaaBo_3SGlHuUhcFOi9kVzQSxBczzppZJy2dGbjeUyfcFb1EBv2myP18gSvb7V-sJ6QkeTFiwvu3n7Iv9Efs50dx_jOYILEU9MZHiS90igoF6Urbg2Pzh0zEb-QAQMX-Qhq7S1vWxQiVmayF0xj-lYEkSScigmPRdadGrWiyIjodfbpF7lZleWgdDrLTfMCT-Eqw2MsMbcm12n46MXQBaoXYOGWe3Tpxi_Lh9ufclih97rF0PT8_K3emgullXbyHexpIK6_NFKlr2vLsA90y1h63fjAasvDQPpnT3uQN50fcM1TJQBLHT3IPEVP-6-eH-N8xjvIXnBZ33-iQTCq1aaHJGPriPvA3HMTRy-KuJdyvEeU9r7ekbFgGjDhm3rGZqPKK22YulwRn7sT1X0-ALDF0GtOBD8